version: '3.8'

services:
  hierarchy-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4321:4321'
    volumes:
      - .:/usr/src/app
    command: [node, 'build/src/server.js']
